package com.kjache.runtime

enum class FailureReason {
    QNN_NOT_AVAILABLE,
    SKELETON_LIBRARY_MISSING,
    DELEGATE_LIBRARY_LOAD_FAILED,
    BACKEND_LIBRARY_LOAD_FAILED,
    DELEGATE_CREATE_FAILED,
    MODEL_LOAD_FAILED,
    INTERPRETER_CREATE_FAILED,
    DELEGATE_ATTACH_FAILED
}
